
services:
  gpricemonitor-api:
    # build: ./backend
    image: ghcr.io/carlosgruthner/gprice-monitor/backend:latest
    container_name: gpricemonitor-api
    ports:
      - "4000:4000"
    volumes:
      - /etc/localtime:/etc/localtime:ro # Sincroniza o relógio com o Linux hospedeiro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/app/data
      - ./backend:/app/data
    environment:
      - TZ=America/Sao_Paulo  # Define o fuso horário para o Node.js
      - DTABASE_PATH=/app/data/precos.db
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_TO=${EMAIL_TO}
    restart: always

  gpricemonitor:
    # build: ./frontend
    image: ghcr.io/carlosgruthner/gprice-monitor/frontend:latest
    container_name: gpricemonitor
    ports:
      - "3000:3000"
    depends_on:
      - gpricemonitor-api
    environment:
      - HOSTNAME=0.0.0.0
      - EXTERNAL_API_IP=172.17.154.235 # Altere o ip da api quando mudar de local
      - EXTERNAL_API_PORT=4000
    restart: always