
services:
  gpricemonitor-backend:
    # build: ./backend
    image: ghcr.io/carlosgruthner/gprice-monitor/backend:latest
    container_name: gpricemonitor-backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app/data
    environment:
      - DTABASE_PATH=/app/data/precos.db
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_TO=${EMAIL_TO}
    restart: always

  gpricemonitor:
    # build: ./frontend
    image: ghcr.io/carlosgruthner/gprice-monitor/frontend:latest
    container_name: gpricemonitor
    ports:
      - "3001:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    restart: always